#!/usr/bin/python3
import json
import os
import sys
import argparse
from bs4 import BeautifulSoup


def err(s, c=1):
    print(s, file=sys.stderr)
    sys.exit(c)


def start_process(xml_file: str):
    try:
        with open(xml_file) as f:
            soup = BeautifulSoup(f, "xml")
        # <dragonshark arch="{...}">{...}</dragonshark> contains everything.
        dragonshark = soup.find("dragonshark")
        # >> <game-id domain="{...}" app="{...}" />.
        game_id = dragonshark.find("game-id")
        domain = game_id.domain
        app = game_id.app
        # >> <command text="{...}">.
        directory = os.path.dirname(xml_file)
        command = dragonshark.find("command").text
    except Exception:
        err("Could not read or understand the manifest file properly", 2)
        return

    with open("/run/game/command-awaiter") as f:
        json.dump({"directory": directory, "command": command, "domain": domain, "app": app}, f)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Launches a Dragonshark-enabled game')
    parser.add_argument('manifest', help='path to the XML manifest file for the game')
    args = parser.parse_args()
    start_process(args.manifest)
